CC = x86_64-w64-mingw32-gcc
CFLAGS = -Wall -Wextra
INCLUDES = -I/usr/include/SDL2/
LIBS = -lSDL2 -lmingw32 -lSDL2main -lSDL2 -mwindows
SRCS = sdl_sample.c
OBJS = $(SRCS:.c=.o)
MAIN = sdl_sample

$(MAIN): $(OBJS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LIBS)

.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean: 
	$(RM) *.o *~ $(MAIN)

