CC = x86_64-w64-mingw32-g++
INCLUDES = -I/usr/include/SDL2/ -I../stb
CFLAGS = -Wall -Wextra -DNDEBUG
LIBS = -L/usr/local/lib/ -L/usr/x86_64-w64-mingw32/sys-root/mingw/lib/ -lSDL2 -lSDL2_image -lm -lSDL2_ttf -lavutil -lmingw32 -lSDL2main -lSDL2 -mwindows
SRCS = sdl_jpg.cpp
OBJS = $(SRCS:.cpp=.o)
MAIN = sdl_jpg

$(MAIN): $(OBJS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LIBS)

.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) $(LIBS) -c $< -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $(LIBS) -c $< -o $@

clean: 
	$(RM) *.o *~ $(MAIN)

